# =============================================================================
# E1.9 pre-change reference pinning
#
# Runs the three deterministic pinning configurations defined in
# tests/testthat/helper-lps-e1-9.R against the CURRENTLY LOADED package source
# and writes their full-precision (hex float) outputs to
# tests/testthat/helper-lps-e1-9-reference.R, together with the provenance of
# the generating tree (git HEAD, R/lps.R sha256, generation timestamp).
#
# PURPOSE: executed once at the last pre-change commit, this freezes the
# "current behavior" that the E1.9 b = 1 backward-compatibility GATE pins
# (contract lps_tiers1to4_contract_2026-06-11.md, sB/E1.9, tau_alg = 1e-10).
# An auditor can re-derive every pinned value by checking out the recorded
# commit and re-running:
#
#     Rscript dev/methods/lps/ci/e1_9_pin_reference_fits.R
#
# The script refuses to run on a dirty R/lps.R unless FORCE=1 is set, so the
# recorded provenance cannot silently disagree with the values.
# =============================================================================

repo <- normalizePath(".")
stopifnot(file.exists(file.path(repo, "DESCRIPTION")),
          file.exists(file.path(repo, "R", "lps.R")))

git.head <- system("git rev-parse HEAD", intern = TRUE)
lps.dirty <- length(system("git status --porcelain -- R/lps.R",
                           intern = TRUE)) > 0L
if (lps.dirty && !identical(Sys.getenv("FORCE"), "1")) {
    stop("R/lps.R has uncommitted changes; reference pinning must run on ",
         "committed source (set FORCE=1 to override).")
}
lps.sha256 <- unname(tools::sha256sum(file.path(repo, "R", "lps.R")))
stamp <- format(Sys.time(), "%Y%m%dT%H%M%SZ", tz = "UTC")

suppressMessages(pkgload::load_all(repo, quiet = TRUE))
source(file.path(repo, "tests", "testthat", "helper-lps-e1-9.R"))

hex <- function(x) {
    paste(deparse(x, control = c("keepNA", "keepInteger", "hexNumeric")),
          collapse = "\n        ")
}

capture.config <- function(fit) {
    list(
        fitted.values = fit$fitted.values,
        cv.rmse.observed = fit$cv.table$cv.rmse.observed,
        cand.support.size = as.integer(fit$cv.table$support.size),
        cand.degree = as.integer(fit$cv.table$degree),
        cand.kernel = as.character(fit$cv.table$kernel),
        selected.support.size = as.integer(fit$selected$support.size[[1L]]),
        selected.degree = as.integer(fit$selected$degree[[1L]]),
        selected.kernel = as.character(fit$selected$kernel[[1L]])
    )
}

emit.config <- function(name, cfg) {
    paste0(
        "    ", name, " = list(\n",
        "        fitted.values = ", hex(cfg$fitted.values), ",\n",
        "        cv.rmse.observed = ", hex(cfg$cv.rmse.observed), ",\n",
        "        cand.support.size = ", hex(cfg$cand.support.size), ",\n",
        "        cand.degree = ", hex(cfg$cand.degree), ",\n",
        "        cand.kernel = ", hex(cfg$cand.kernel), ",\n",
        "        selected.support.size = ", hex(cfg$selected.support.size),
        ",\n",
        "        selected.degree = ", hex(cfg$selected.degree), ",\n",
        "        selected.kernel = ", hex(cfg$selected.kernel), "\n",
        "    )"
    )
}

message("Fitting configuration A (multi-candidate ambient) ...")
A <- capture.config(e19.fit.A())
message("Fitting configuration B (strict singleton ambient) ...")
B <- capture.config(e19.fit.B())
message("Fitting configuration C (local-PCA singleton) ...")
C <- capture.config(e19.fit.C())

out.path <- file.path(repo, "tests", "testthat",
                      "helper-lps-e1-9-reference.R")
header <- c(
    "# Generated by dev/methods/lps/ci/e1_9_pin_reference_fits.R -- DO NOT EDIT.",
    "# Pre-change reference values for the E1.9 b = 1 backward-compatibility",
    "# GATE (hex floats; exact doubles).",
    paste0("# generation_commit: ", git.head),
    paste0("# generation_r_lps_sha256: ", lps.sha256),
    paste0("# generated_utc: ", stamp),
    paste0("# r_version: ", R.version.string),
    paste0("# blas: ", extSoftVersion()[["BLAS"]]),
    paste0("# lapack: ", La_library()),
    ""
)
body <- paste0(
    "e19.reference <- list(\n",
    paste(c(emit.config("A", A), emit.config("B", B), emit.config("C", C)),
          collapse = ",\n"),
    "\n)\n"
)
writeLines(c(header, body), out.path)
message("Wrote ", out.path)
message("generation_commit: ", git.head)
message("generation_r_lps_sha256: ", lps.sha256)
