# Render the Tier-2 (E2.14 + E2.12) results report, HTML + PDF.
#
# Report source:  <report dir>/scripts/lps_tier2_binary_hygiene_report.Rmd
# Outputs:        <report dir>/lps_tier2_binary_hygiene_report_2026-06-11.html
#                 <report dir>/lps_tier2_binary_hygiene_report_2026-06-11.pdf
# where <report dir> = dev/methods/lps/reports/tier2/binary_hygiene/2026-06-11
# (both outputs committed on the Tier-2 branch).
#
# The report consumes only committed CSV artifacts -- the report-specific
# inputs under <report dir>/inputs/ (generated by
# scripts/export_tier2_report_inputs.R beside this file) and the gate/study
# evidence under reports/ (generated by the committed validation/ scripts);
# rendering performs no result computation. The PDF build uses the MacTeX
# xelatex via /Library/TeX/texbin (prepended to PATH below if missing);
# figures are vector (cairo_pdf) in the PDF and raster (ragg_png) in the
# HTML.
#
# Run from the package root:
#   Rscript dev/methods/lps/reports/tier2/binary_hygiene/2026-06-11/scripts/render_lps_tier2_binary_hygiene_report.R

build.datetime <- format(Sys.time(), "%Y-%m-%d %H:%M:%S %Z",
                         tz = "America/New_York")
Sys.setenv(BUILD_DATETIME = build.datetime)

texbin <- "/Library/TeX/texbin"
if (dir.exists(texbin) &&
    !grepl(texbin, Sys.getenv("PATH"), fixed = TRUE)) {
    Sys.setenv(PATH = paste(texbin, Sys.getenv("PATH"), sep = ":"))
}

report.dir <- file.path("dev", "methods", "lps", "reports", "tier2",
                        "binary_hygiene", "2026-06-11")
input <- file.path(report.dir, "scripts",
                   "lps_tier2_binary_hygiene_report.Rmd")

rmarkdown::render(
    input = input,
    output_format = "html_document",
    output_file = "lps_tier2_binary_hygiene_report_2026-06-11.html",
    output_dir = report.dir,
    knit_root_dir = normalizePath("."),
    quiet = TRUE
)
cat("rendered", file.path(report.dir,
    "lps_tier2_binary_hygiene_report_2026-06-11.html"),
    "at", build.datetime, "\n")

rmarkdown::render(
    input = input,
    output_format = "pdf_document",
    output_file = "lps_tier2_binary_hygiene_report_2026-06-11.pdf",
    output_dir = report.dir,
    knit_root_dir = normalizePath("."),
    quiet = TRUE
)
cat("rendered", file.path(report.dir,
    "lps_tier2_binary_hygiene_report_2026-06-11.pdf"),
    "at", build.datetime, "\n")
