# Generated by validation/e1_9_pin_reference_fits.R -- DO NOT EDIT.
# Pre-change reference values for the E1.9 b = 1 backward-compatibility
# GATE (hex floats; exact doubles).
# generation_commit: fe582b1d683a3b724503bcaa55f39bb142ceab3d
# generation_r_lps_sha256: 8bc0abdb1baf588bfef908df41db4514df7f356fd0ab3dd929438958fbf27549
# generated_utc: 20260611T053818Z
# r_version: R version 4.5.2 (2025-10-31)
# blas: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
# lapack: /Library/Frameworks/R.framework/Versions/4.5-arm64/Resources/lib/libRlapack.dylib

e19.reference <- list(
    A = list(
        fitted.values = c(-0x1.08bb74433ac8bp-2, -0x1.a8e0f11d808cep-1, -0x1.0ea3fae732238p-2, 
        -0x1.552fc05210f14p-1, 0x1.c08e9944fc49dp+0, 0x1.6ca0d3762ad4bp-2, 
        -0x1.75d56d7140a62p-1, 0x1.b920108cc957ap-1, 0x1.7bdf49d53d082p-1, 
        -0x1.74310a957009fp-3, -0x1.3e5568397dd61p+0, 0x1.d41286fe62225p-1, 
        0x1.030aff555c09ap-1, 0x1.53689ee98e414p+0, -0x1.2719c6bf3c781p+0, 
        0x1.3976c60c4ee08p-3, 0x1.53299bb5a02cp-3, 0x1.5d567194df245p-1, 
        0x1.1aebbce81e36bp+0, 0x1.1b6318909f016p-1, 0x1.2d32ef91bdb9bp-2, 
        0x1.28078717e2c98p-2, -0x1.4b3f7efaa072p-1, 0x1.33c47bd7721eap+0, 
        -0x1.c83cc1f554134p-2, 0x1.1280da1415c99p+0, 0x1.c2b5539d4f86cp-2, 
        0x1.06a768a6086f7p+0, 0x1.af9754b8904c6p+0, 0x1.7f4a1e2690e1bp+0, 
        -0x1.58d94aa017374p-1, 0x1.b2277d98791p+0, 0x1.0a1d0b16ab0ep+0, 
        0x1.282e88b374c7cp+0, -0x1.4c6e0ea950746p+0, 0x1.b5f631303aa5ep-1, 
        0x1.a92a464117eacp-3, 0x1.a57d77bc91a1cp-1, 0x1.6595aa6307f63p+0, 
        0x1.183f2ebd88b49p-5, -0x1.abea24ef7e71p-9, 0x1.a6e5a9ca1ab01p-3, 
        0x1.75a1a9ee6ee22p-1, 0x1.3ca9f9030f41p-1, -0x1.725bfcaf22475p-2, 
        -0x1.e908ed7dfcfa6p-2, 0x1.39c5072289e0ep+0, 0x1.7bdeda6406011p-2, 
        0x1.79f7e0449c725p+0, 0x1.1729dd96aaaadp+0, 0x1.f3a2d5083e4a3p-1, 
        0x1.152ba9511af29p+0, -0x1.91ce6f1c48f1fp-2, 0x1.a64a3c64be9d5p-5, 
        0x1.303f676e2b0c6p+0, -0x1.0424f30d226efp+0, 0x1.c9c0b9d3b97cap-1, 
        0x1.293187b95ad4ap-3, 0x1.9ed0b97e6e914p-2, 0x1.661040b203a83p-1
        ),
        cv.rmse.observed = c(0x1.031a2dae8c0d9p-2, 0x1.6d4d8a60675c6p-2, 0x1.f581b7096cf37p-4, 
        0x1.08a799d0bbe3ep-3, 0x1.f740b045873f5p-4, 0x1.c2bf84f1673fap-4, 
        0x1.b3a863f0040e7p-3, 0x1.047f7a0d0e5c2p-2, 0x1.ed7c1995265f6p-4, 
        0x1.eba03db00a6c6p-4, 0x1.609584a31c95cp-3, 0x1.07034290fc87bp-3, 
        0x1.d34c0b7e455e7p-3, 0x1.2a3db0b9a672p-2, 0x1.eeed742ff1562p-4, 
        0x1.f840c4747f60bp-4, 0x1.241002fdb3f76p-3, 0x1.eac38987eb586p-4, 
        0x1.bd5fb99e91f22p-3, 0x1.16db6af9c31p-2, 0x1.eb1eed136700dp-4, 
        0x1.ed994d77de59dp-4, 0x1.2c58d3b322cf3p-3, 0x1.f22196d684f3ep-4
        ),
        cand.support.size = c(12L, 20L, 12L, 20L, 12L, 20L, 12L, 20L, 12L, 20L, 12L, 20L, 
        12L, 20L, 12L, 20L, 12L, 20L, 12L, 20L, 12L, 20L, 12L, 20L),
        cand.degree = c(0L, 0L, 1L, 1L, 2L, 2L, 0L, 0L, 1L, 1L, 2L, 2L, 0L, 0L, 1L, 
        1L, 2L, 2L, 0L, 0L, 1L, 1L, 2L, 2L),
        cand.kernel = c("gaussian", "gaussian", "gaussian", "gaussian", "gaussian", 
        "gaussian", "tricube", "tricube", "tricube", "tricube", "tricube", 
        "tricube", "epanechnikov", "epanechnikov", "epanechnikov", "epanechnikov", 
        "epanechnikov", "epanechnikov", "triangular", "triangular", "triangular", 
        "triangular", "triangular", "triangular"),
        selected.support.size = 20L,
        selected.degree = 2L,
        selected.kernel = "gaussian"
    ),
    B = list(
        fitted.values = c(-0x1.1664ac131383bp-2, -0x1.97796b5c66778p-1, -0x1.03578293f962p-2, 
        -0x1.4fe28b9dce5f9p-1, 0x1.c516c9a6a3812p+0, 0x1.70a8d29272146p-2, 
        -0x1.6ad88627c8358p-1, 0x1.b943584c29e7ap-1, 0x1.884bba8bc0722p-1, 
        -0x1.ae998ca0b5c61p-3, -0x1.3a90ba758777bp+0, 0x1.d06b265218e14p-1, 
        0x1.080f49b439618p-1, 0x1.4741ee8e1ba68p+0, -0x1.23cb410011acep+0, 
        0x1.15b557df39949p-3, 0x1.646db74d85a36p-3, 0x1.6181978538e9ap-1, 
        0x1.21359d898ef7ep+0, 0x1.0d813e28d064ep-1, 0x1.2b3757518b521p-2, 
        0x1.17d305738da0dp-2, -0x1.5f7c723387bb4p-1, 0x1.2e9911023e8cfp+0, 
        -0x1.bce72bc8a52eap-2, 0x1.1342cf36f5352p+0, 0x1.cf6cb08c5142p-2, 
        0x1.04c2fe584d469p+0, 0x1.9a04864a80e0ep+0, 0x1.75eebc0a33b87p+0, 
        -0x1.5be5b9bb155c9p-1, 0x1.9f1d2ff57d50cp+0, 0x1.0aa96ce04883ap+0, 
        0x1.3068475f61e0bp+0, -0x1.439f3d5923e98p+0, 0x1.a77dbcdef53e3p-1, 
        0x1.5380ddb513a53p-3, 0x1.9743a8a62f024p-1, 0x1.629778d1bd641p+0, 
        0x1.fd19afcd36d3p-6, -0x1.d5b3972ed16ecp-7, 0x1.8846fd7800d22p-3, 
        0x1.763324ea198a4p-1, 0x1.4383b300320b4p-1, -0x1.5fd73524f9ecdp-2, 
        -0x1.ee0e3ca8b0951p-2, 0x1.323dddac800b2p+0, 0x1.8c95fadc10bdfp-2, 
        0x1.70535ba0d430cp+0, 0x1.1a4a5509c466ap+0, 0x1.f45e6d8852d9ep-1, 
        0x1.0d115d87c9fa6p+0, -0x1.8ca7278121a3bp-2, -0x1.a647728a7493fp-8, 
        0x1.374a95b5539f9p+0, -0x1.0f6115add9af5p+0, 0x1.cc5a18cc1d968p-1, 
        0x1.261aa91ce1e36p-3, 0x1.d279a999206c9p-2, 0x1.718e303673c1dp-1
        ),
        cv.rmse.observed = 0x1.297b07ba266ebp-3,
        cand.support.size = 18L,
        cand.degree = 1L,
        cand.kernel = "tricube",
        selected.support.size = 18L,
        selected.degree = 1L,
        selected.kernel = "tricube"
    ),
    C = list(
        fitted.values = c(0x1.be4b9b14a3b04p-2, 0x1.6bbe232054f97p+0, 0x1.61a143dda477fp-1, 
        0x1.291a0194c8464p+0, -0x1.16080bf5a560bp+0, 0x1.5439dd9878ecp+0, 
        0x1.36fdcb34347f3p-1, -0x1.7e8319f238a5ep+0, 0x1.2f2a7bb08ae76p+0, 
        0x1.82203243a283cp+0, 0x1.40d6e43a5d308p-1, 0x1.ba868d801618p-3, 
        -0x1.ff39f92321ab9p-1, 0x1.5954edfb45e08p+0, -0x1.24197c17b55bap-4, 
        0x1.7f524f0c72a26p+0, 0x1.83c69a29ed4e3p-1, 0x1.9c801e1e1b72dp-2, 
        0x1.86d3949e34d59p+0, 0x1.20176f6628ea7p-2, 0x1.617a762d97609p+0, 
        -0x1.387954961e7b1p-1, -0x1.c1148ee660411p-2, 0x1.71e510a56dadfp-1, 
        0x1.a250d1bac5d97p-3, -0x1.196a16f6c886bp+0, -0x1.4a958f2f03c46p-2, 
        -0x1.ebd93eb71bd37p-5, -0x1.0e8f3de0fbebep-1, 0x1.7a42e639476dep-2, 
        0x1.098b5b410f52cp-2, 0x1.25a78a90aba83p-1, 0x1.73d8b336354ecp-1, 
        0x1.64dc191a73fdep+0, 0x1.abb2d21fc5dafp-1, 0x1.8eb27f6f187ap-1, 
        -0x1.3dce714c4f38fp+0, 0x1.ac29b07df1768p-2, 0x1.f27b84bb309cdp-2, 
        -0x1.9c9bc895a650ep-3, 0x1.cfdf5f618cfd6p-1, 0x1.974f750701ba7p-2, 
        -0x1.a6b68788bfd81p-2, 0x1.33ad4cd623de1p-1, 0x1.d29ddab049396p-1, 
        0x1.47d11671322e2p-2, 0x1.1c38f9a3adb19p-2, 0x1.1ef0c4e284b3cp-2, 
        -0x1.c501041c41e17p-3, -0x1.983843708442ep-4),
        cv.rmse.observed = 0x1.ee9f87e5500cfp-4,
        cand.support.size = 16L,
        cand.degree = 1L,
        cand.kernel = "gaussian",
        selected.support.size = 16L,
        selected.degree = 1L,
        selected.kernel = "gaussian"
    )
)

