test_that("source-root detection distinguishes source, installation and name-only directories", {
  root <- tempfile("geosmooth-root-"); dir.create(root)
  withr::defer(unlink(root, recursive=TRUE))
  writeLines("Package: geosmooth", file.path(root,"DESCRIPTION"))
  expect_null(geosmooth.test.source.root(starts=root))
  dir.create(file.path(root,"R"))
  writeLines("# generated R source",file.path(root,"R","RcppExports.R"))
  expect_identical(geosmooth.test.source.root(starts=root),normalizePath(root))
  dir.create(file.path(root,"tests"))
  expect_identical(geosmooth.test.source.root(starts=file.path(root,"tests")),normalizePath(root))
  dir.create(file.path(root,"Meta"));saveRDS(list(),file.path(root,"Meta","package.rds"))
  expect_null(geosmooth.test.source.root(starts=root))
  unlink(file.path(root,"Meta"),recursive=TRUE)
  writeLines("Package: unrelated",file.path(root,"DESCRIPTION"))
  expect_null(geosmooth.test.source.root(starts=root))
})
