#!/usr/bin/env python3
"""Generate the geosmooth development dashboard.

The dashboard is a generated navigation surface for development notes, project
briefs, shared/archive references, and selected method reports under ``dev/``.
Source Markdown and report artifacts remain canonical; files under
``dev/html/`` are generated.
"""

from __future__ import annotations

import datetime as dt
import html
import os
from pathlib import Path
import re
from urllib.parse import quote


SCRIPT_PATH = Path(__file__).resolve()
DEV_ROOT = SCRIPT_PATH.parents[1]
DASHBOARD_DIR = DEV_ROOT / "html"
ASSETS_DIR = DASHBOARD_DIR / "assets"
NOTES_ROOT = DEV_ROOT / "notes"
PROJECT_BRIEFS_ROOT = DEV_ROOT / "project_briefs"
METHODS_ROOT = DEV_ROOT / "methods"
SHARED_ROOT = DEV_ROOT / "shared"
ARCHIVE_ROOT = DEV_ROOT / "archive"
GENERATED_COMMENT = "Generated by dev/scripts/build_dev_dashboard.py. Do not edit by hand."
REPORT_EXTENSIONS = {".html", ".pdf"}


def rel_posix(path: Path, start: Path) -> str:
    return os.path.relpath(path, start).replace(os.sep, "/")


def href_to(path: Path, start: Path = DASHBOARD_DIR) -> str:
    rel = rel_posix(path, start)
    return quote(rel, safe="/#:.?=&%")


def friendly_path(path: Path | str) -> str:
    raw = path.as_posix() if isinstance(path, Path) else str(path)
    if raw in {"", "."}:
        return "Root"
    return " / ".join(friendly_name(part) for part in raw.split("/"))


def friendly_name(value: str) -> str:
    if value.upper() == "README":
        return "README"
    return value.replace("_", " ").replace("-", " ").title()


def title_from_filename(path: Path) -> str:
    stem = path.stem
    if stem.upper() == "README":
        return friendly_name(path.parent.name)
    return friendly_name(stem)


def extract_markdown_title(path: Path, text: str) -> str:
    for line in text.splitlines():
        match = re.match(r"^#\s+(.+?)\s*$", line)
        if match:
            return re.sub(r"\s+", " ", match.group(1)).strip()
    return title_from_filename(path)


def extract_markdown_summary(text: str, limit: int = 190) -> str:
    in_fence = False
    chunks: list[str] = []
    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith(("```", "~~~")):
            in_fence = not in_fence
            continue
        if in_fence or not stripped or stripped.startswith("#"):
            continue
        if stripped in {"---", "***"} or stripped.startswith("|"):
            continue
        cleaned = re.sub(r"!\[[^\]]*\]\([^)]+\)", "", stripped)
        cleaned = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", cleaned)
        cleaned = re.sub(r"[`*_>#]", "", cleaned)
        chunks.append(cleaned)
        if sum(len(chunk) for chunk in chunks) >= limit:
            break
    summary = re.sub(r"\s+", " ", " ".join(chunks)).strip()
    if len(summary) > limit:
        summary = summary[: limit - 1].rstrip() + "..."
    return summary


def read_markdown_entry(path: Path, root: Path) -> dict[str, str]:
    text = path.read_text(encoding="utf-8", errors="replace")
    rel = path.relative_to(root)
    return {
        "title": extract_markdown_title(path, text),
        "summary": extract_markdown_summary(text),
        "path": path.as_posix(),
        "rel": rel.as_posix(),
        "folder": rel.parent.as_posix() if rel.parent.as_posix() != "." else "",
        "href": href_to(path),
    }


def discover_markdown(root: Path) -> list[dict[str, str]]:
    if not root.exists():
        return []
    entries: list[dict[str, str]] = []
    for path in sorted(root.rglob("*.md")):
        rel_parts = path.relative_to(root).parts
        if any(part in {"html", ".git"} for part in rel_parts):
            continue
        entries.append(read_markdown_entry(path, root))
    return entries


def discover_reports() -> list[dict[str, object]]:
    if not METHODS_ROOT.exists():
        return []
    groups: dict[tuple[str, str], list[Path]] = {}
    for method_dir in sorted(path for path in METHODS_ROOT.iterdir() if path.is_dir()):
        reports_root = method_dir / "reports"
        if not reports_root.exists():
            continue
        for path in sorted(reports_root.rglob("*")):
            if not path.is_file() or path.suffix.lower() not in REPORT_EXTENSIONS:
                continue
            rel_parent = path.parent.relative_to(reports_root).as_posix()
            key = (method_dir.name, "" if rel_parent == "." else rel_parent)
            groups.setdefault(key, []).append(path)

    report_groups: list[dict[str, object]] = []
    for (method, rel_folder), files in sorted(groups.items()):
        label = friendly_path(rel_folder) if rel_folder else "Reports"
        report_groups.append(
            {
                "method": method,
                "folder": rel_folder,
                "label": label,
                "files": [
                    {
                        "title": title_from_filename(path),
                        "kind": path.suffix.lower().lstrip("."),
                        "rel": path.relative_to(DEV_ROOT).as_posix(),
                        "href": href_to(path),
                    }
                    for path in files
                ],
            }
        )
    return report_groups


def group_by_folder(entries: list[dict[str, str]]) -> dict[str, list[dict[str, str]]]:
    grouped: dict[str, list[dict[str, str]]] = {}
    for entry in entries:
        grouped.setdefault(entry["folder"], []).append(entry)
    return dict(sorted(grouped.items(), key=lambda item: item[0]))


def build_markdown_tree(entries: list[dict[str, str]], empty_message: str) -> str:
    if not entries:
        return f'<p class="empty">{html.escape(empty_message)}</p>'

    parts: list[str] = ['<div class="tree-list">']
    grouped = group_by_folder(entries)
    for folder, folder_entries in grouped.items():
        folder_label = friendly_path(folder)
        open_attr = " open" if folder in {"", "lps", "ps_lps"} else ""
        parts.append(f'<details class="folder"{open_attr}>')
        parts.append(
            f'<summary><span>{html.escape(folder_label)}</span>'
            f'<span class="count">{len(folder_entries)}</span></summary>'
        )
        parts.append("<ul>")
        for entry in folder_entries:
            search_text = " ".join(
                [entry["title"], entry["summary"], entry["rel"]]
            ).lower()
            parts.append(
                '<li class="entry" data-search="'
                + html.escape(search_text, quote=True)
                + '">'
            )
            parts.append(
                f'<a href="{html.escape(entry["href"], quote=True)}">'
                f'{html.escape(entry["title"])}</a>'
            )
            parts.append(f'<span class="path">{html.escape(entry["rel"])}</span>')
            if entry["summary"]:
                parts.append(f'<p>{html.escape(entry["summary"])}</p>')
            parts.append("</li>")
        parts.append("</ul>")
        parts.append("</details>")
    parts.append("</div>")
    return "\n".join(parts)


def build_report_tree(report_groups: list[dict[str, object]]) -> str:
    if not report_groups:
        return '<p class="empty">No method reports have been indexed under dev/methods/*/reports yet.</p>'

    by_method: dict[str, list[dict[str, object]]] = {}
    for group in report_groups:
        by_method.setdefault(str(group["method"]), []).append(group)

    parts: list[str] = ['<div class="tree-list">']
    for method, groups in sorted(by_method.items()):
        parts.append('<details class="folder" open>')
        parts.append(
            f'<summary><span>{html.escape(friendly_name(method))}</span>'
            f'<span class="count">{sum(len(group["files"]) for group in groups)}</span></summary>'
        )
        parts.append("<div class=\"nested-folders\">")
        for group in groups:
            files = group["files"]
            label = str(group["label"])
            parts.append('<details class="folder report-folder" open>')
            parts.append(
                f'<summary><span>{html.escape(label)}</span>'
                f'<span class="count">{len(files)}</span></summary>'
            )
            parts.append("<ul>")
            for file_entry in files:
                search_text = " ".join(
                    [
                        method,
                        label,
                        str(file_entry["title"]),
                        str(file_entry["rel"]),
                    ]
                ).lower()
                parts.append(
                    '<li class="entry" data-search="'
                    + html.escape(search_text, quote=True)
                    + '">'
                )
                parts.append(
                    f'<a href="{html.escape(str(file_entry["href"]), quote=True)}">'
                    f'{html.escape(str(file_entry["title"]))}</a>'
                    f'<span class="badge">{html.escape(str(file_entry["kind"]).upper())}</span>'
                )
                parts.append(f'<span class="path">{html.escape(str(file_entry["rel"]))}</span>')
                parts.append("</li>")
            parts.append("</ul>")
            parts.append("</details>")
        parts.append("</div>")
        parts.append("</details>")
    parts.append("</div>")
    return "\n".join(parts)


def build_section(
    section_id: str,
    title: str,
    summary: str,
    count: int,
    body: str,
) -> str:
    return f"""
      <section class="panel" id="{html.escape(section_id, quote=True)}">
        <div class="panel-heading">
          <div>
            <h2>{html.escape(title)}</h2>
            <p>{html.escape(summary)}</p>
          </div>
          <span class="metric">{count}</span>
        </div>
        {body}
      </section>
"""


def build_dashboard(
    notes: list[dict[str, str]],
    project_briefs: list[dict[str, str]],
    shared_refs: list[dict[str, str]],
    archive_refs: list[dict[str, str]],
    reports: list[dict[str, object]],
    generated_at: str,
) -> str:
    notes_body = build_markdown_tree(
        notes,
        "No development notes have been added under dev/notes yet.",
    )
    briefs_body = build_markdown_tree(
        project_briefs,
        "No project briefs have been added under dev/project_briefs yet.",
    )
    shared_body = build_markdown_tree(
        shared_refs,
        "No shared development references have been added under dev/shared yet.",
    )
    archive_body = build_markdown_tree(
        archive_refs,
        "No retained archive Markdown files have been added under dev/archive yet.",
    )
    reports_body = build_report_tree(reports)

    sections = [
        build_section(
            "notes",
            "Notes",
            "Durable explanations, design memos, prompts, plans, and tutorials.",
            len(notes),
            notes_body,
        ),
        build_section(
            "project-briefs",
            "Project Briefs",
            "Repository-level briefs and cross-method coordination.",
            len(project_briefs),
            briefs_body,
        ),
        build_section(
            "shared",
            "Shared Assets",
            "Cross-method DGPs, registries, fixtures, benchmark specs, and dataset manifests.",
            len(shared_refs),
            shared_body,
        ),
        build_section(
            "archive",
            "Archive",
            "Retained historical bundles that may be promoted into canonical homes.",
            len(archive_refs),
            archive_body,
        ),
        build_section(
            "method-reports",
            "Method Reports",
            "Selected generated HTML/PDF reports under method workspaces.",
            sum(len(group["files"]) for group in reports),
            reports_body,
        ),
    ]

    return f"""<!doctype html>
<!-- {GENERATED_COMMENT} -->
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>geosmooth Dev Dashboard</title>
  <link rel="stylesheet" href="assets/geosmooth-dev-dashboard.css">
</head>
<body>
  <header class="hero">
    <div>
      <p class="eyebrow">geosmooth</p>
      <h1>Development Dashboard</h1>
      <p class="lede">A generated map of notes, project briefs, shared assets, retained archive references, and method reports.</p>
    </div>
    <div class="build-meta">
      <span>Generated</span>
      <strong>{html.escape(generated_at)}</strong>
    </div>
  </header>

  <main>
    <nav class="quick-links" aria-label="Dashboard sections">
      <a href="#notes">Notes <span>{len(notes)}</span></a>
      <a href="#project-briefs">Project Briefs <span>{len(project_briefs)}</span></a>
      <a href="#shared">Shared Assets <span>{len(shared_refs)}</span></a>
      <a href="#archive">Archive <span>{len(archive_refs)}</span></a>
      <a href="#method-reports">Method Reports <span>{sum(len(group["files"]) for group in reports)}</span></a>
    </nav>

    <div class="toolbar">
      <label for="dashboard-search">Search</label>
      <input id="dashboard-search" type="search" placeholder="Filter titles, paths, and summaries">
      <button type="button" id="expand-all">Expand</button>
      <button type="button" id="collapse-all">Collapse</button>
    </div>

    <div class="panels">
{''.join(sections)}
    </div>
  </main>

  <footer>
    <span>{html.escape(GENERATED_COMMENT)}</span>
  </footer>
  <script src="assets/geosmooth-dev-dashboard.js"></script>
</body>
</html>
"""


def build_redirect() -> str:
    return f"""<!doctype html>
<!-- {GENERATED_COMMENT} -->
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="refresh" content="0; url=html/index.html">
  <link rel="canonical" href="html/index.html">
  <title>geosmooth Dev Dashboard</title>
</head>
<body>
  <p><a href="html/index.html">Open the geosmooth development dashboard</a></p>
</body>
</html>
"""


def build_css() -> str:
    return f"""/* {GENERATED_COMMENT} */
:root {{
  color-scheme: light;
  --bg: #f7f7f4;
  --surface: #ffffff;
  --text: #1d2528;
  --muted: #667276;
  --line: #dfe4e2;
  --accent: #216b6b;
  --accent-soft: #dbeeed;
  --warn: #8c5d16;
  --shadow: 0 12px 32px rgba(27, 39, 42, 0.08);
}}

* {{
  box-sizing: border-box;
}}

body {{
  margin: 0;
  background: var(--bg);
  color: var(--text);
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
  line-height: 1.5;
}}

a {{
  color: var(--accent);
  text-decoration-thickness: 1px;
  text-underline-offset: 3px;
}}

.hero {{
  display: flex;
  justify-content: space-between;
  gap: 24px;
  align-items: flex-end;
  padding: 40px max(24px, calc((100vw - 1180px) / 2)) 26px;
  background: #10292d;
  color: #f8fbfa;
}}

.eyebrow {{
  margin: 0 0 4px;
  color: #a7d2cf;
  font-size: 13px;
  text-transform: uppercase;
  letter-spacing: 0;
  font-weight: 700;
}}

h1 {{
  margin: 0;
  font-size: 34px;
  line-height: 1.1;
  letter-spacing: 0;
}}

.lede {{
  max-width: 680px;
  margin: 10px 0 0;
  color: #d7e6e4;
  font-size: 16px;
}}

.build-meta {{
  min-width: 210px;
  border-left: 1px solid rgba(255, 255, 255, 0.28);
  padding-left: 18px;
  color: #d7e6e4;
  font-size: 13px;
}}

.build-meta span,
.build-meta strong {{
  display: block;
}}

main {{
  width: min(1180px, calc(100vw - 40px));
  margin: 22px auto 44px;
}}

.quick-links {{
  display: grid;
  grid-template-columns: repeat(auto-fit, minmax(190px, 1fr));
  gap: 12px;
  margin-bottom: 16px;
}}

.quick-links a {{
  display: flex;
  justify-content: space-between;
  align-items: center;
  min-height: 52px;
  padding: 12px 14px;
  background: var(--surface);
  border: 1px solid var(--line);
  border-radius: 8px;
  color: var(--text);
  text-decoration: none;
  box-shadow: 0 1px 0 rgba(16, 41, 45, 0.03);
}}

.quick-links span,
.metric,
.count,
.badge {{
  display: inline-flex;
  align-items: center;
  justify-content: center;
  min-width: 28px;
  height: 24px;
  border-radius: 999px;
  background: var(--accent-soft);
  color: var(--accent);
  font-size: 12px;
  font-weight: 700;
}}

.toolbar {{
  display: grid;
  grid-template-columns: auto minmax(220px, 1fr) auto auto;
  gap: 8px;
  align-items: center;
  padding: 10px;
  margin-bottom: 18px;
  background: var(--surface);
  border: 1px solid var(--line);
  border-radius: 8px;
}}

.toolbar label {{
  color: var(--muted);
  font-size: 13px;
  font-weight: 700;
}}

input,
button {{
  height: 36px;
  border: 1px solid var(--line);
  border-radius: 6px;
  font: inherit;
}}

input {{
  width: 100%;
  padding: 0 10px;
  color: var(--text);
}}

button {{
  padding: 0 12px;
  background: #f3f7f6;
  color: var(--text);
  cursor: pointer;
}}

.panels {{
  display: grid;
  gap: 16px;
}}

.panel {{
  background: var(--surface);
  border: 1px solid var(--line);
  border-radius: 8px;
  box-shadow: var(--shadow);
  overflow: hidden;
}}

.panel-heading {{
  display: flex;
  justify-content: space-between;
  gap: 18px;
  align-items: flex-start;
  padding: 18px 18px 12px;
  border-bottom: 1px solid var(--line);
}}

h2 {{
  margin: 0;
  font-size: 20px;
  letter-spacing: 0;
}}

.panel-heading p {{
  margin: 4px 0 0;
  color: var(--muted);
}}

.metric {{
  min-width: 38px;
  height: 30px;
  font-size: 14px;
}}

.tree-list {{
  padding: 8px 14px 16px;
}}

details.folder {{
  border-bottom: 1px solid var(--line);
}}

details.folder:last-child {{
  border-bottom: 0;
}}

summary {{
  display: flex;
  justify-content: space-between;
  align-items: center;
  gap: 12px;
  min-height: 42px;
  cursor: pointer;
  font-weight: 700;
}}

.nested-folders {{
  margin-left: 16px;
  border-left: 2px solid var(--accent-soft);
  padding-left: 12px;
}}

ul {{
  list-style: none;
  margin: 0;
  padding: 0 0 8px;
}}

.entry {{
  padding: 10px 0;
}}

.entry + .entry {{
  border-top: 1px solid #edf0ee;
}}

.entry a {{
  font-weight: 700;
}}

.path {{
  display: block;
  margin-top: 3px;
  color: var(--muted);
  font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
  font-size: 12px;
  overflow-wrap: anywhere;
}}

.entry p {{
  margin: 6px 0 0;
  color: var(--muted);
  font-size: 14px;
}}

.badge {{
  margin-left: 8px;
  min-width: 34px;
  height: 20px;
  background: #f7ead4;
  color: var(--warn);
}}

.empty {{
  margin: 0;
  padding: 16px 18px 20px;
  color: var(--muted);
}}

.is-hidden {{
  display: none;
}}

footer {{
  width: min(1180px, calc(100vw - 40px));
  margin: 0 auto 26px;
  color: var(--muted);
  font-size: 12px;
}}

@media (max-width: 760px) {{
  .hero {{
    display: block;
    padding-top: 28px;
  }}

  .build-meta {{
    margin-top: 18px;
    border-left: 0;
    padding-left: 0;
  }}

  .quick-links,
  .toolbar {{
    grid-template-columns: 1fr;
  }}
}}
"""


def build_js() -> str:
    return f"""// {GENERATED_COMMENT}
(function () {{
  const search = document.getElementById("dashboard-search");
  const expand = document.getElementById("expand-all");
  const collapse = document.getElementById("collapse-all");

  function setAll(open) {{
    document.querySelectorAll("details.folder").forEach((detail) => {{
      detail.open = open;
    }});
  }}

  function filterEntries() {{
    const query = (search.value || "").trim().toLowerCase();
    const entries = Array.from(document.querySelectorAll(".entry"));
    entries.forEach((entry) => {{
      const haystack = entry.getAttribute("data-search") || entry.textContent.toLowerCase();
      const matched = !query || haystack.includes(query);
      entry.classList.toggle("is-hidden", !matched);
      if (matched && query) {{
        let parent = entry.parentElement;
        while (parent) {{
          if (parent.tagName === "DETAILS") {{
            parent.open = true;
          }}
          parent = parent.parentElement;
        }}
      }}
    }});

    document.querySelectorAll("details.folder").forEach((detail) => {{
      const visible = detail.querySelector(".entry:not(.is-hidden)");
      detail.classList.toggle("is-hidden", Boolean(query) && !visible);
    }});
  }}

  search.addEventListener("input", filterEntries);
  expand.addEventListener("click", () => setAll(true));
  collapse.addEventListener("click", () => setAll(false));
}}());
"""


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def main() -> None:
    generated_at = dt.datetime.now().astimezone().strftime("%Y-%m-%d %H:%M:%S %Z")
    notes = discover_markdown(NOTES_ROOT)
    project_briefs = discover_markdown(PROJECT_BRIEFS_ROOT)
    shared_refs = discover_markdown(SHARED_ROOT)
    archive_refs = discover_markdown(ARCHIVE_ROOT)
    reports = discover_reports()

    write_text(
        DASHBOARD_DIR / "index.html",
        build_dashboard(
            notes,
            project_briefs,
            shared_refs,
            archive_refs,
            reports,
            generated_at,
        ),
    )
    write_text(DEV_ROOT / "index.html", build_redirect())
    write_text(ASSETS_DIR / "geosmooth-dev-dashboard.css", build_css())
    write_text(ASSETS_DIR / "geosmooth-dev-dashboard.js", build_js())

    print(f"Dashboard: {DASHBOARD_DIR / 'index.html'}")
    print(f"Notes: {len(notes)}")
    print(f"Project briefs: {len(project_briefs)}")
    print(f"Shared references: {len(shared_refs)}")
    print(f"Archive references: {len(archive_refs)}")
    print(f"Report files: {sum(len(group['files']) for group in reports)}")


if __name__ == "__main__":
    main()
