# Tier-2 report input export (E2.14 + E2.12)
#
# Results-generation script for the Tier-2 HTML report
# (validation/lps_tier2_binary_hygiene_report.Rmd). It regenerates, fully
# deterministically, every CSV the report consumes and writes them under
# reports/, together with a manifest recording the generation timestamp, git
# head, and SHA-256 checksums. The report itself never recomputes results
# (style guide: separate generation from reporting).
#
# The fixtures are NOT re-defined here: the script sources the committed
# GATE test files with `test_that` shadowed to a no-op, so the exported
# inputs come from exactly the gated fixture constructors
# (tests/testthat/test-lps-binary-separation.R,
#  tests/testthat/test-lps-binary-metric-consistency.R).
#
# Cross-check: when a Tier-2 execution bundle directory is passed as the
# first argument (e.g. audit_artifacts/tier2_20260611T084642Z), the
# regenerated E2.12/E2.14 aggregates are compared against the bundle's CSVs
# and the outcome is recorded in the manifest.
#
# Run (from the package root, on the committed tree):
#   Rscript validation/export_tier2_report_inputs.R [BUNDLE_DIR]
#
# Outputs (all under reports/):
#   e2_14_fixture.csv             z, weights, labels of both fixture arms
#   e2_14_deviance_traces.csv     post-fix solver trace per arm
#   e2_14_solver_summary.csv      post-fix per-arm solver summary
#   e2_14_fallback_telemetry.csv  exact-separation fallback telemetry
#   e2_12_fixture_a.csv           G6 seed-2121 draw (x1, p, y)
#   e2_12a_selection_metric.csv   per-candidate raw vs deployed scores
#   e2_12b_contributions.csv      per-point log-loss contributions
#   e2_12b_clip_dominance.csv     per-candidate dominance aggregates
#   e2_12b_fit_accounting.csv     binomial CV logistic telemetry
#   tier2_report_inputs_manifest.txt
#
# (reports/e2_14_prefix_newton_overshoot.csv and the cross-clip STUDY CSVs
#  are generated by their own committed scripts and are consumed as-is.)

args <- commandArgs(trailingOnly = TRUE)
BUNDLE <- if (length(args) >= 1L) args[[1L]] else ""

suppressMessages(pkgload::load_all(".", quiet = TRUE))
dir.create("reports", showWarnings = FALSE)

test_that <- function(...) invisible(NULL)          # shadow
suppressWarnings(source("tests/testthat/test-lps-binary-separation.R",
                        local = TRUE))
suppressWarnings(source("tests/testthat/test-lps-binary-metric-consistency.R",
                        local = TRUE))

out.files <- character(0)
emit <- function(df, name) {
    path <- file.path("reports", name)
    utils::write.csv(df, path, row.names = FALSE)
    out.files <<- c(out.files, path)
    path
}

## ---- E2.14 ------------------------------------------------------------------
fx.near <- e214.fixture(flip = TRUE)
fx.exact <- e214.fixture(flip = FALSE)
emit(data.frame(
    index = seq_along(fx.near$y),
    z = fx.near$design[, 2L],
    weight = fx.near$weights,
    y.near.separable = fx.near$y,
    y.exactly.separable = fx.exact$y,
    flipped = seq_along(fx.near$y) == 2L
), "e2_14_fixture.csv")

arms <- list(near.separable = fx.near, exactly.separable = fx.exact)
trace.rows <- list()
summary.rows <- list()
for (arm in names(arms)) {
    solved <- e214.solve(arms[[arm]])
    increases <- diff(solved$deviance.trace)
    trace.rows[[arm]] <- data.frame(
        arm = arm,
        iteration = seq_along(solved$deviance.trace) - 1L,
        deviance = solved$deviance.trace
    )
    summary.rows[[arm]] <- data.frame(
        arm = arm,
        status = solved$status,
        converged = isTRUE(solved$converged),
        iterations = solved$iterations,
        step.halvings = solved$step.halvings,
        max.deviance.increase = max(increases),
        prediction = if (!is.null(solved$prediction)) {
            solved$prediction[[1L]]
        } else NA_real_
    )
}
emit(do.call(rbind, trace.rows), "e2_14_deviance_traces.csv")
e214.summary <- do.call(rbind, summary.rows)
emit(e214.summary, "e2_14_solver_summary.csv")

fallback.rows <- lapply(c("mean", "na"), function(action) {
    telemetry <- geosmooth:::.klp.logistic.telemetry.new("binomial")
    fitted <- geosmooth:::.klp.fit.logistic.prob.design(
        design = fx.exact$design, y = fx.exact$y, weights = fx.exact$weights,
        design.basis = "orthogonal.polynomial.drop", design.drop.tol = 1e-8,
        ridge.multiplier.grid = 0, ridge.condition.max = Inf,
        unstable.action = action, logistic.telemetry = telemetry
    )
    s <- geosmooth:::.klp.logistic.telemetry.summary(telemetry)
    data.frame(unstable.action = action, fitted = fitted,
               fitted.is.na = is.na(fitted), attempted = s$attempted,
               converged = s$converged,
               fallback.path.count = s$fallback.path.count,
               event.rate.fallback.count = s$event.rate.fallback.count,
               na.failure.count = s$na.failure.count,
               weighted.event.rate = stats::weighted.mean(fx.exact$y,
                                                          fx.exact$weights))
})
emit(do.call(rbind, fallback.rows), "e2_14_fallback_telemetry.csv")

## ---- E2.12 (a) ----------------------------------------------------------------
g.a <- e212.g6(seed = 2121L)
emit(data.frame(index = seq_along(g.a$y), x1 = g.a$X[, 1L],
                p = g.a$p, y = g.a$y),
     "e2_12_fixture_a.csv")
fit.a <- fit.lps(
    X = g.a$X, y = g.a$y, foldid = g.a$foldid,
    support.grid = c(8L, 60L), degree.grid = c(0L, 2L),
    kernel.grid = "gaussian", coordinate.method = "coordinates",
    backend = "R", design.basis = "orthogonal.polynomial.drop",
    ridge.multiplier.grid = 0, ridge.condition.max = Inf,
    unstable.action = "mean", outcome.family = "bernoulli",
    keep.cv.predictions = TRUE
)
ct.a <- fit.a$cv.table
pred.a <- fit.a$cv.predictions
stopifnot(all(is.finite(pred.a)))
deployed.a <- vapply(seq_len(ncol(pred.a)), function(j) {
    mean((g.a$y - pmin(1, pmax(0, pred.a[, j])))^2)
}, numeric(1L))
e212a <- data.frame(
    candidate = seq_len(nrow(ct.a)),
    support.size = ct.a$support.size, degree = ct.a$degree,
    kernel = ct.a$kernel,
    raw.brier = ct.a$cv.rmse.observed^2,
    cv.brier.observed = ct.a$cv.brier.observed,
    deployed.clipped.brier = deployed.a,
    equality.residual = abs(ct.a$cv.brier.observed - deployed.a),
    n.pred.below.0 = vapply(seq_len(ncol(pred.a)),
                            function(j) sum(pred.a[, j] < 0), integer(1L)),
    n.pred.above.1 = vapply(seq_len(ncol(pred.a)),
                            function(j) sum(pred.a[, j] > 1), integer(1L)),
    selected = seq_len(nrow(ct.a)) == which(
        ct.a$support.size == fit.a$selected$support.size[[1L]] &
            ct.a$degree == fit.a$selected$degree[[1L]] &
            ct.a$kernel == fit.a$selected$kernel[[1L]])
)
emit(e212a, "e2_12a_selection_metric.csv")

## ---- E2.12 (b) ----------------------------------------------------------------
g.b <- e212.g6(seed = 7001L)
flip <- 7L
stopifnot(identical(g.b$y[[flip]], 0L), g.b$X[flip, 1L] < -0.5)
y.b <- g.b$y
y.b[[flip]] <- 1
fit.b <- fit.lps(
    X = g.b$X, y = y.b, foldid = g.b$foldid,
    support.grid = 60L, degree.grid = c(0L, 1L),
    kernel.grid = "gaussian", coordinate.method = "coordinates",
    backend = "R", design.basis = "orthogonal.polynomial.drop",
    ridge.multiplier.grid = 0, ridge.condition.max = Inf,
    unstable.action = "mean", outcome.family = "binomial",
    keep.cv.predictions = TRUE
)
ct.b <- fit.b$cv.table
pred.b <- fit.b$cv.predictions
stopifnot(all(is.finite(pred.b)))
clip.at <- function(p, eps) pmin(1 - eps, pmax(eps, p))
contrib.at <- function(p, y, eps) {
    pc <- clip.at(p, eps)
    -(y * log(pc) + (1 - y) * log1p(-pc))
}
contrib.long <- do.call(rbind, lapply(seq_len(nrow(ct.b)), function(j) {
    data.frame(
        candidate = j,
        support.size = ct.b$support.size[[j]], degree = ct.b$degree[[j]],
        index = seq_along(y.b), y = y.b,
        cv.prediction = pred.b[, j],
        contrib.clip.1e.15 = contrib.at(pred.b[, j], y.b, 1e-15),
        contrib.clip.1e.6 = contrib.at(pred.b[, j], y.b, 1e-6),
        flipped = seq_along(y.b) == flip
    )
}))
emit(contrib.long, "e2_12b_contributions.csv")

manual.logloss <- function(p, y, eps) mean(contrib.at(p, y, eps))
e212b <- do.call(rbind, lapply(seq_len(nrow(ct.b)), function(j) {
    binders <- which((y.b == 1 & pred.b[, j] < 1e-6) |
                         (y.b == 0 & pred.b[, j] > 1 - 1e-6))
    swing.total <- manual.logloss(pred.b[, j], y.b, 1e-15) -
        manual.logloss(pred.b[, j], y.b, 1e-6)
    swing.point <- (contrib.at(pred.b[flip, j], 1, 1e-15) -
                        contrib.at(pred.b[flip, j], 1, 1e-6)) / length(y.b)
    c15 <- contrib.at(pred.b[, j], y.b, 1e-15)
    data.frame(
        candidate = j,
        support.size = ct.b$support.size[[j]], degree = ct.b$degree[[j]],
        logloss.1e.15 = manual.logloss(pred.b[, j], y.b, 1e-15),
        logloss.1e.6 = manual.logloss(pred.b[, j], y.b, 1e-6),
        logloss.1e.3 = manual.logloss(pred.b[, j], y.b, 1e-3),
        cv.logloss.observed = ct.b$cv.logloss.observed[[j]],
        n.wrong.side.binders = length(binders),
        binder.is.flip = identical(binders, flip),
        flip.prediction = pred.b[flip, j],
        flip.share.of.crossclip.swing = swing.point / swing.total,
        flip.contrib.1e.15 = c15[[flip]],
        max.other.contrib.1e.15 = max(c15[-flip]),
        selected = ct.b$support.size[[j]] ==
            fit.b$selected$support.size[[1L]] &&
            ct.b$degree[[j]] == fit.b$selected$degree[[1L]]
    )
}))
emit(e212b, "e2_12b_clip_dominance.csv")

cv.tel <- fit.b$logistic.diagnostics$cv
emit(data.frame(
    scope = "cv",
    attempted = cv.tel$attempted,
    converged = cv.tel$converged,
    failed = cv.tel$failed,
    fallback.path.count = cv.tel$fallback.path.count,
    event.rate.fallback.count = cv.tel$event.rate.fallback.count,
    na.failure.count = cv.tel$na.failure.count,
    convergence.fraction = cv.tel$convergence.fraction,
    fallback.path.fraction = cv.tel$fallback.path.fraction
), "e2_12b_fit_accounting.csv")

## ---- Bundle cross-check --------------------------------------------------------
crosscheck <- "skipped (no bundle directory supplied or found)"
if (nzchar(BUNDLE) && dir.exists(BUNDLE)) {
    ok <- TRUE
    msgs <- character(0)
    ba <- file.path(BUNDLE, "e2_12a_selection_metric.csv")
    if (file.exists(ba)) {
        bdl <- utils::read.csv(ba)
        d <- max(abs(bdl$cv.brier.observed - e212a$cv.brier.observed),
                 abs(bdl$cv.rmse.observed^2 - e212a$raw.brier))
        ok <- ok && d < 1e-12
        msgs <- c(msgs, sprintf("e2_12a max |diff| = %.3e", d))
    }
    bt <- file.path(BUNDLE, "e2_14_deviance_traces.csv")
    if (file.exists(bt)) {
        bdl <- utils::read.csv(bt)
        mine <- do.call(rbind, trace.rows)
        d <- max(abs(bdl$deviance - mine$deviance))
        ok <- ok && identical(nrow(bdl), nrow(mine)) && d < 1e-12
        msgs <- c(msgs, sprintf("e2_14 traces max |diff| = %.3e", d))
    }
    crosscheck <- sprintf("%s vs %s: %s", if (ok) "ok" else "MISMATCH",
                          BUNDLE, paste(msgs, collapse = "; "))
}

## ---- Manifest -------------------------------------------------------------------
sha <- vapply(out.files, function(f) {
    unname(unlist(strsplit(system2("shasum", c("-a", "256", f),
                                   stdout = TRUE), "\\s+"))[[1L]])
}, character(1L))
git.head <- system2("git", c("rev-parse", "HEAD"), stdout = TRUE)
git.dirty <- length(system2("git", c("status", "--porcelain"),
                            stdout = TRUE)) > 0L
manifest <- c(
    sprintf("results_generated_utc: %s",
            format(Sys.time(), "%Y-%m-%dT%H:%M:%SZ", tz = "UTC")),
    sprintf("results_generated_eastern: %s",
            format(Sys.time(), "%Y-%m-%d %H:%M:%S %Z",
                   tz = "America/New_York")),
    sprintf("git_head: %s", git.head),
    sprintf("tree_clean: %s", !git.dirty),
    sprintf("r_version: %s", R.version.string),
    sprintf("blas: %s", extSoftVersion()[["BLAS"]]),
    sprintf("bundle_crosscheck: %s", crosscheck),
    "files:",
    sprintf("  %s  %s", sha, out.files)
)
writeLines(manifest, "reports/tier2_report_inputs_manifest.txt")
cat(paste(manifest, collapse = "\n"), "\n")
cat("wrote", length(out.files), "CSV files + manifest under reports/\n")
