// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rcpp_geosmooth_native_stub
bool rcpp_geosmooth_native_stub();
RcppExport SEXP _geosmooth_rcpp_geosmooth_native_stub() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_geosmooth_native_stub());
    return rcpp_result_gen;
END_RCPP
}
// rcpp_kernel_local_polynomial_cv_coordinates
NumericVector rcpp_kernel_local_polynomial_cv_coordinates(const NumericMatrix& X, const NumericVector& y, const IntegerVector& foldid, const IntegerVector& support_size, const IntegerVector& degree, const CharacterVector& kernel);
RcppExport SEXP _geosmooth_rcpp_kernel_local_polynomial_cv_coordinates(SEXP XSEXP, SEXP ySEXP, SEXP foldidSEXP, SEXP support_sizeSEXP, SEXP degreeSEXP, SEXP kernelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type foldid(foldidSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type support_size(support_sizeSEXP);
    Rcpp::traits::input_parameter< const IntegerVector& >::type degree(degreeSEXP);
    Rcpp::traits::input_parameter< const CharacterVector& >::type kernel(kernelSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_kernel_local_polynomial_cv_coordinates(X, y, foldid, support_size, degree, kernel));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_kernel_local_polynomial_predict_coordinates
NumericVector rcpp_kernel_local_polynomial_predict_coordinates(const NumericMatrix& X_train, const NumericVector& y_train, const NumericMatrix& X_eval, const int support_size, const int degree, const std::string& kernel);
RcppExport SEXP _geosmooth_rcpp_kernel_local_polynomial_predict_coordinates(SEXP X_trainSEXP, SEXP y_trainSEXP, SEXP X_evalSEXP, SEXP support_sizeSEXP, SEXP degreeSEXP, SEXP kernelSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type X_train(X_trainSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type y_train(y_trainSEXP);
    Rcpp::traits::input_parameter< const NumericMatrix& >::type X_eval(X_evalSEXP);
    Rcpp::traits::input_parameter< const int >::type support_size(support_sizeSEXP);
    Rcpp::traits::input_parameter< const int >::type degree(degreeSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type kernel(kernelSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_kernel_local_polynomial_predict_coordinates(X_train, y_train, X_eval, support_size, degree, kernel));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_local_pca_chart
List rcpp_local_pca_chart(const NumericMatrix& X_support, const NumericVector& center, const int chart_dim, const std::string& center_mode, const std::string& dim_rule, const double eigen_tolerance, Nullable<NumericVector> weights, const bool rebase_to_anchor, const bool orient_basis);
RcppExport SEXP _geosmooth_rcpp_local_pca_chart(SEXP X_supportSEXP, SEXP centerSEXP, SEXP chart_dimSEXP, SEXP center_modeSEXP, SEXP dim_ruleSEXP, SEXP eigen_toleranceSEXP, SEXP weightsSEXP, SEXP rebase_to_anchorSEXP, SEXP orient_basisSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type X_support(X_supportSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type center(centerSEXP);
    Rcpp::traits::input_parameter< const int >::type chart_dim(chart_dimSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type center_mode(center_modeSEXP);
    Rcpp::traits::input_parameter< const std::string& >::type dim_rule(dim_ruleSEXP);
    Rcpp::traits::input_parameter< const double >::type eigen_tolerance(eigen_toleranceSEXP);
    Rcpp::traits::input_parameter< Nullable<NumericVector> >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< const bool >::type rebase_to_anchor(rebase_to_anchorSEXP);
    Rcpp::traits::input_parameter< const bool >::type orient_basis(orient_basisSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_local_pca_chart(X_support, center, chart_dim, center_mode, dim_rule, eigen_tolerance, weights, rebase_to_anchor, orient_basis));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_metric_graph_lowpass_operator
SEXP rcpp_metric_graph_lowpass_operator(SEXP s_adj_list, SEXP s_weight_list, SEXP s_conductance_rule, SEXP s_conductance_epsilon, SEXP s_conductance_alpha, SEXP s_conductance_sigma, SEXP s_sigma_rule, SEXP s_sigma_quantile, SEXP s_local_k, SEXP s_laplacian_type);
RcppExport SEXP _geosmooth_rcpp_metric_graph_lowpass_operator(SEXP s_adj_listSEXP, SEXP s_weight_listSEXP, SEXP s_conductance_ruleSEXP, SEXP s_conductance_epsilonSEXP, SEXP s_conductance_alphaSEXP, SEXP s_conductance_sigmaSEXP, SEXP s_sigma_ruleSEXP, SEXP s_sigma_quantileSEXP, SEXP s_local_kSEXP, SEXP s_laplacian_typeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type s_adj_list(s_adj_listSEXP);
    Rcpp::traits::input_parameter< SEXP >::type s_weight_list(s_weight_listSEXP);
    Rcpp::traits::input_parameter< SEXP >::type s_conductance_rule(s_conductance_ruleSEXP);
    Rcpp::traits::input_parameter< SEXP >::type s_conductance_epsilon(s_conductance_epsilonSEXP);
    Rcpp::traits::input_parameter< SEXP >::type s_conductance_alpha(s_conductance_alphaSEXP);
    Rcpp::traits::input_parameter< SEXP >::type s_conductance_sigma(s_conductance_sigmaSEXP);
    Rcpp::traits::input_parameter< SEXP >::type s_sigma_rule(s_sigma_ruleSEXP);
    Rcpp::traits::input_parameter< SEXP >::type s_sigma_quantile(s_sigma_quantileSEXP);
    Rcpp::traits::input_parameter< SEXP >::type s_local_k(s_local_kSEXP);
    Rcpp::traits::input_parameter< SEXP >::type s_laplacian_type(s_laplacian_typeSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_metric_graph_lowpass_operator(s_adj_list, s_weight_list, s_conductance_rule, s_conductance_epsilon, s_conductance_alpha, s_conductance_sigma, s_sigma_rule, s_sigma_quantile, s_local_k, s_laplacian_type));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_metric_graph_lowpass_spectrum
SEXP rcpp_metric_graph_lowpass_spectrum(SEXP s_adj_list, SEXP s_weight_list, SEXP s_conductance_rule, SEXP s_conductance_epsilon, SEXP s_conductance_alpha, SEXP s_conductance_sigma, SEXP s_sigma_rule, SEXP s_sigma_quantile, SEXP s_local_k, SEXP s_laplacian_type, SEXP s_n_eigenpairs, SEXP s_eigen_solver, SEXP s_dense_eigen_threshold, SEXP s_dense_fallback_threshold, SEXP s_dense_fallback, SEXP s_verbose);
RcppExport SEXP _geosmooth_rcpp_metric_graph_lowpass_spectrum(SEXP s_adj_listSEXP, SEXP s_weight_listSEXP, SEXP s_conductance_ruleSEXP, SEXP s_conductance_epsilonSEXP, SEXP s_conductance_alphaSEXP, SEXP s_conductance_sigmaSEXP, SEXP s_sigma_ruleSEXP, SEXP s_sigma_quantileSEXP, SEXP s_local_kSEXP, SEXP s_laplacian_typeSEXP, SEXP s_n_eigenpairsSEXP, SEXP s_eigen_solverSEXP, SEXP s_dense_eigen_thresholdSEXP, SEXP s_dense_fallback_thresholdSEXP, SEXP s_dense_fallbackSEXP, SEXP s_verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type s_adj_list(s_adj_listSEXP);
    Rcpp::traits::input_parameter< SEXP >::type s_weight_list(s_weight_listSEXP);
    Rcpp::traits::input_parameter< SEXP >::type s_conductance_rule(s_conductance_ruleSEXP);
    Rcpp::traits::input_parameter< SEXP >::type s_conductance_epsilon(s_conductance_epsilonSEXP);
    Rcpp::traits::input_parameter< SEXP >::type s_conductance_alpha(s_conductance_alphaSEXP);
    Rcpp::traits::input_parameter< SEXP >::type s_conductance_sigma(s_conductance_sigmaSEXP);
    Rcpp::traits::input_parameter< SEXP >::type s_sigma_rule(s_sigma_ruleSEXP);
    Rcpp::traits::input_parameter< SEXP >::type s_sigma_quantile(s_sigma_quantileSEXP);
    Rcpp::traits::input_parameter< SEXP >::type s_local_k(s_local_kSEXP);
    Rcpp::traits::input_parameter< SEXP >::type s_laplacian_type(s_laplacian_typeSEXP);
    Rcpp::traits::input_parameter< SEXP >::type s_n_eigenpairs(s_n_eigenpairsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type s_eigen_solver(s_eigen_solverSEXP);
    Rcpp::traits::input_parameter< SEXP >::type s_dense_eigen_threshold(s_dense_eigen_thresholdSEXP);
    Rcpp::traits::input_parameter< SEXP >::type s_dense_fallback_threshold(s_dense_fallback_thresholdSEXP);
    Rcpp::traits::input_parameter< SEXP >::type s_dense_fallback(s_dense_fallbackSEXP);
    Rcpp::traits::input_parameter< SEXP >::type s_verbose(s_verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_metric_graph_lowpass_spectrum(s_adj_list, s_weight_list, s_conductance_rule, s_conductance_epsilon, s_conductance_alpha, s_conductance_sigma, s_sigma_rule, s_sigma_quantile, s_local_k, s_laplacian_type, s_n_eigenpairs, s_eigen_solver, s_dense_eigen_threshold, s_dense_fallback_threshold, s_dense_fallback, s_verbose));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_ssrhe_hessian_operator
SEXP rcpp_ssrhe_hessian_operator(SEXP s_X, SEXP s_k, SEXP s_tangent_dim, SEXP s_nn_index, SEXP s_support_index, SEXP s_tangent_dim_rule, SEXP s_eigen_tolerance, SEXP s_derivative_order, SEXP s_stabilizer, SEXP s_pinv_tol, SEXP s_local_solver, SEXP s_normal_equations_max_condition, SEXP s_verbose);
RcppExport SEXP _geosmooth_rcpp_ssrhe_hessian_operator(SEXP s_XSEXP, SEXP s_kSEXP, SEXP s_tangent_dimSEXP, SEXP s_nn_indexSEXP, SEXP s_support_indexSEXP, SEXP s_tangent_dim_ruleSEXP, SEXP s_eigen_toleranceSEXP, SEXP s_derivative_orderSEXP, SEXP s_stabilizerSEXP, SEXP s_pinv_tolSEXP, SEXP s_local_solverSEXP, SEXP s_normal_equations_max_conditionSEXP, SEXP s_verboseSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type s_X(s_XSEXP);
    Rcpp::traits::input_parameter< SEXP >::type s_k(s_kSEXP);
    Rcpp::traits::input_parameter< SEXP >::type s_tangent_dim(s_tangent_dimSEXP);
    Rcpp::traits::input_parameter< SEXP >::type s_nn_index(s_nn_indexSEXP);
    Rcpp::traits::input_parameter< SEXP >::type s_support_index(s_support_indexSEXP);
    Rcpp::traits::input_parameter< SEXP >::type s_tangent_dim_rule(s_tangent_dim_ruleSEXP);
    Rcpp::traits::input_parameter< SEXP >::type s_eigen_tolerance(s_eigen_toleranceSEXP);
    Rcpp::traits::input_parameter< SEXP >::type s_derivative_order(s_derivative_orderSEXP);
    Rcpp::traits::input_parameter< SEXP >::type s_stabilizer(s_stabilizerSEXP);
    Rcpp::traits::input_parameter< SEXP >::type s_pinv_tol(s_pinv_tolSEXP);
    Rcpp::traits::input_parameter< SEXP >::type s_local_solver(s_local_solverSEXP);
    Rcpp::traits::input_parameter< SEXP >::type s_normal_equations_max_condition(s_normal_equations_max_conditionSEXP);
    Rcpp::traits::input_parameter< SEXP >::type s_verbose(s_verboseSEXP);
    rcpp_result_gen = Rcpp::wrap(rcpp_ssrhe_hessian_operator(s_X, s_k, s_tangent_dim, s_nn_index, s_support_index, s_tangent_dim_rule, s_eigen_tolerance, s_derivative_order, s_stabilizer, s_pinv_tol, s_local_solver, s_normal_equations_max_condition, s_verbose));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_geosmooth_rcpp_geosmooth_native_stub", (DL_FUNC) &_geosmooth_rcpp_geosmooth_native_stub, 0},
    {"_geosmooth_rcpp_kernel_local_polynomial_cv_coordinates", (DL_FUNC) &_geosmooth_rcpp_kernel_local_polynomial_cv_coordinates, 6},
    {"_geosmooth_rcpp_kernel_local_polynomial_predict_coordinates", (DL_FUNC) &_geosmooth_rcpp_kernel_local_polynomial_predict_coordinates, 6},
    {"_geosmooth_rcpp_local_pca_chart", (DL_FUNC) &_geosmooth_rcpp_local_pca_chart, 9},
    {"_geosmooth_rcpp_metric_graph_lowpass_operator", (DL_FUNC) &_geosmooth_rcpp_metric_graph_lowpass_operator, 10},
    {"_geosmooth_rcpp_metric_graph_lowpass_spectrum", (DL_FUNC) &_geosmooth_rcpp_metric_graph_lowpass_spectrum, 16},
    {"_geosmooth_rcpp_ssrhe_hessian_operator", (DL_FUNC) &_geosmooth_rcpp_ssrhe_hessian_operator, 13},
    {NULL, NULL, 0}
};

RcppExport void R_init_geosmooth(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
