# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' GE0 native scaffold stub
#'
#' Internal native scaffold check.
#'
#' @keywords internal
rcpp_geosmooth_native_stub <- function() {
    .Call(`_geosmooth_rcpp_geosmooth_native_stub`)
}

#' Kernel local polynomial CV RMSE for ambient coordinates
#'
#' Internal C++ backend for `kernel.local.polynomial.cv()`.
#'
#' @keywords internal
rcpp_kernel_local_polynomial_cv_coordinates <- function(X, y, foldid, support_size, degree, kernel) {
    .Call(`_geosmooth_rcpp_kernel_local_polynomial_cv_coordinates`, X, y, foldid, support_size, degree, kernel)
}

#' Kernel local polynomial predictions for ambient coordinates
#'
#' Internal C++ backend for `kernel.local.polynomial.cv()`.
#'
#' @keywords internal
rcpp_kernel_local_polynomial_predict_coordinates <- function(X_train, y_train, X_eval, support_size, degree, kernel) {
    .Call(`_geosmooth_rcpp_kernel_local_polynomial_predict_coordinates`, X_train, y_train, X_eval, support_size, degree, kernel)
}

#' Local PCA chart
#'
#' Internal C++ backend for shared local-PCA chart construction.
#'
#' @keywords internal
rcpp_local_pca_chart <- function(X_support, center, chart_dim, center_mode = "anchor", dim_rule = "fixed", eigen_tolerance = 0.9, weights = NULL, rebase_to_anchor = TRUE, orient_basis = FALSE) {
    .Call(`_geosmooth_rcpp_local_pca_chart`, X_support, center, chart_dim, center_mode, dim_rule, eigen_tolerance, weights, rebase_to_anchor, orient_basis)
}

#' SSRHE Hessian operator native backend
#'
#' Internal native backend for `ssrhe.hessian.operator()`.
#'
#' @keywords internal
rcpp_ssrhe_hessian_operator <- function(s_X, s_k, s_tangent_dim, s_nn_index, s_support_index, s_tangent_dim_rule, s_eigen_tolerance, s_derivative_order, s_stabilizer, s_pinv_tol, s_local_solver, s_normal_equations_max_condition, s_verbose) {
    .Call(`_geosmooth_rcpp_ssrhe_hessian_operator`, s_X, s_k, s_tangent_dim, s_nn_index, s_support_index, s_tangent_dim_rule, s_eigen_tolerance, s_derivative_order, s_stabilizer, s_pinv_tol, s_local_solver, s_normal_equations_max_condition, s_verbose)
}

