# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' GE0 native scaffold stub
#'
#' Internal native scaffold check.
#'
#' @keywords internal
rcpp_geosmooth_native_stub <- function() {
    .Call(`_geosmooth_rcpp_geosmooth_native_stub`)
}

#' Native graph harmonic smoothing backend
#'
#' Internal C++ backend for `perform.harmonic.smoothing()`.
#'
#' @keywords internal
rcpp_perform_harmonic_smoothing <- function(adj_list, weight_list, values, region_vertices, max_iterations, tolerance) {
    .Call(`_geosmooth_rcpp_perform_harmonic_smoothing`, adj_list, weight_list, values, region_vertices, max_iterations, tolerance)
}

#' Kernel local polynomial CV RMSE for ambient coordinates
#'
#' Internal C++ backend for `fit.lps()`.
#'
#' @keywords internal
rcpp_kernel_local_polynomial_cv_coordinates <- function(X, y, foldid, support_size, degree, kernel) {
    .Call(`_geosmooth_rcpp_kernel_local_polynomial_cv_coordinates`, X, y, foldid, support_size, degree, kernel)
}

#' Kernel local polynomial predictions for ambient coordinates
#'
#' Internal C++ backend for `fit.lps()`.
#'
#' @keywords internal
rcpp_kernel_local_polynomial_predict_coordinates <- function(X_train, y_train, X_eval, support_size, degree, kernel) {
    .Call(`_geosmooth_rcpp_kernel_local_polynomial_predict_coordinates`, X_train, y_train, X_eval, support_size, degree, kernel)
}

#' Local PCA chart
#'
#' Internal C++ backend for shared local-PCA chart construction.
#'
#' @keywords internal
rcpp_local_pca_chart <- function(X_support, center, chart_dim, center_mode = "anchor", dim_rule = "fixed", eigen_tolerance = 0.9, weights = NULL, rebase_to_anchor = TRUE, orient_basis = FALSE) {
    .Call(`_geosmooth_rcpp_local_pca_chart`, X_support, center, chart_dim, center_mode, dim_rule, eigen_tolerance, weights, rebase_to_anchor, orient_basis)
}

rcpp_metric_graph_lowpass_operator <- function(s_adj_list, s_weight_list, s_conductance_rule, s_conductance_epsilon, s_conductance_alpha, s_conductance_sigma, s_sigma_rule, s_sigma_quantile, s_local_k, s_laplacian_type) {
    .Call(`_geosmooth_rcpp_metric_graph_lowpass_operator`, s_adj_list, s_weight_list, s_conductance_rule, s_conductance_epsilon, s_conductance_alpha, s_conductance_sigma, s_sigma_rule, s_sigma_quantile, s_local_k, s_laplacian_type)
}

rcpp_metric_graph_lowpass_spectrum <- function(s_adj_list, s_weight_list, s_conductance_rule, s_conductance_epsilon, s_conductance_alpha, s_conductance_sigma, s_sigma_rule, s_sigma_quantile, s_local_k, s_laplacian_type, s_n_eigenpairs, s_eigen_solver, s_dense_eigen_threshold, s_dense_fallback_threshold, s_dense_fallback, s_verbose) {
    .Call(`_geosmooth_rcpp_metric_graph_lowpass_spectrum`, s_adj_list, s_weight_list, s_conductance_rule, s_conductance_epsilon, s_conductance_alpha, s_conductance_sigma, s_sigma_rule, s_sigma_quantile, s_local_k, s_laplacian_type, s_n_eigenpairs, s_eigen_solver, s_dense_eigen_threshold, s_dense_fallback_threshold, s_dense_fallback, s_verbose)
}

#' SSRHE Hessian operator native backend
#'
#' Internal native backend for `ssrhe.hessian.operator()`.
#'
#' @keywords internal
rcpp_ssrhe_hessian_operator <- function(s_X, s_k, s_tangent_dim, s_nn_index, s_support_index, s_tangent_dim_rule, s_eigen_tolerance, s_derivative_order, s_stabilizer, s_pinv_tol, s_local_solver, s_normal_equations_max_condition, s_verbose) {
    .Call(`_geosmooth_rcpp_ssrhe_hessian_operator`, s_X, s_k, s_tangent_dim, s_nn_index, s_support_index, s_tangent_dim_rule, s_eigen_tolerance, s_derivative_order, s_stabilizer, s_pinv_tol, s_local_solver, s_normal_equations_max_condition, s_verbose)
}

